version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOO_ENABLE_AUTH=no
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9080
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9080
    ports:
      - '9080:9080'
    depends_on:
      - zookeeper